"""Add embedding column to the persona

Revision ID: 6618773f5200
Revises: 26f3257e5712
Create Date: 2025-12-14 23:49:25.499783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6618773f5200'
down_revision: Union[str, Sequence[str], None] = '26f3257e5712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'embedding')
    # ### end Alembic commands ###
